version: '3'

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama_network
    devices:
      - /dev/kfd
      - /dev/dri
    # Uncomment and set these if your AMD GPU requires them:
    # environment:
    #   HSA_OVERRIDE_GFX_VERSION: "10.3.0"
    #   HCC_AMDGPU_TARGET: "gfx1030"

  caddy:
    image: caddy:2
    container_name: caddy
    environment:
      - API_TOKEN=${API_TOKEN:?API token is required}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama_network

volumes:
  ollama_data:
  caddy_data:
  caddy_config:

networks:
  ollama_network:
